name: greentick
description: Greentick technology assignment

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get: ^4.6.1
  cached_network_image: ^3.2.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
          weight: 400


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
